-- modeldb.lua
-- Maps WoW model IDs to model filenames and optional variation textures
-- Useful for NPC voiceovers or portraits

ModelDB = {
    [4]   = { model = "murloc2.m2", variation = nil },
    [13]  = { model = "hufmcitizenlow.m2", variation = nil },
    [14]  = { model = "hufmcitizenmid.m2", variation = nil },
    [15]  = { model = "hufmmerchant.m2", variation = nil },
    [16]  = { model = "humanthief.m2", variation = "humanthiefskin.blp" },
    [17]  = { model = "humlblacksmith.m2", variation = nil },
    [18]  = { model = "humlmagicsmith.m2", variation = nil },
    [19]  = { model = "humlmerchant.m2", variation = nil },
    [20]  = { model = "humluppercitizen.m2", variation = nil },
    [21]  = { model = "humscitizenmid.m2", variation = "humanmalecitizenlow.blp" },
    [22]  = { model = "humscitizenmid.m2", variation = "humanmalecitizenlow.blp" },
    [23]  = { model = "humsmerchant.m2", variation = nil },
    [26]  = { model = "kobold2.m2", variation = "kobold2_normal.blp" },
    [31]  = { model = "murloc2.m2", variation = "murloc2_green.blp" },
    [33]  = { model = "ogremage.m2", variation = "ogreskinbeige.blp" },
    [38]  = { model = "tallstrider2.m2", variation = "tallstrider2_turquoise.blp" },
    [40]  = { model = "titanmale.m2", variation = "titanmaleskin01.blp" },
    [42]  = { model = "troll.m2", variation = "trollskinjunglebloodscalpmelee.blp" },
    [49]  = { model = "humanmale.m2", variation = nil },
    [50]  = { model = "humanfemale.m2", variation = nil },
    [51]  = { model = "orcmale.m2", variation = nil },
    [52]  = { model = "orcfemale.m2", variation = nil },
    [53]  = { model = "dwarfmale.m2", variation = nil },
    [54]  = { model = "dwarffemale.m2", variation = nil },
    [55]  = { model = "nightelfmale.m2", variation = nil },
    [56]  = { model = "nightelffemale.m2", variation = nil },
    [57]  = { model = "scourgemale.m2", variation = nil },
    [58]  = { model = "scourgefemale.m2", variation = nil },
    [59]  = { model = "taurenmale.m2", variation = nil },
    [60]  = { model = "taurenfemale.m2", variation = nil },
    [62]  = { model = "hydra.m2", variation = "hydraskinblue.blp" },
    [64]  = { model = "murloc2.m2", variation = nil },
    [65]  = { model = "horse3.m2", variation = "horse3_black.blp" },
    [68]  = { model = "doomguard2.m2", variation = "doomguard2_body_blue.blp" },
    [69]  = { model = "elementalearth2.m2", variation = "elementalearth2_brown.blp" },
    [71]  = { model = "harvestgolem2.m2", variation = "harvestgolem2_brown.blp" },
    [73]  = { model = "direwolf.m2", variation = "direwolfskindarkblack.blp" },
    [74]  = { model = "humscitizenmid.m2", variation = "humanmalecitizenlow.blp" },
    [80]  = { model = "humanfemalekid2.m2", variation = "humanfemalekid2.blp" },
    [86]  = { model = "humscitizenmid.m2", variation = "humanmalecitizenlow.blp" },
    [87]  = { model = "humscitizenmid.m2", variation = "humanmalecitizenlow.blp" },
    [88]  = { model = "humscitizenmid.m2", variation = "humanmalecitizenlow.blp" },
    [89]  = { model = "humanmalepeasantwood.m2", variation = "humanmalepeasantlightskin.blp" },
    -- Add the remaining entries here following the same pattern
}
